---
name: "Dev Infra Build"

on:
  repository_dispatch:
    types: [ dev-deploy-event ]
    
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      terraform_version: "1.6.2"
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.DEV_REGION }}

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3

      - name: "Terraform installation"
        uses: hashicorp/setup-terraform@v3
        with:
          version: ${{ env.terraform_version }}

      - name: "Terraform init"
        run: |
          terraform init \
          -backend-config="bucket=${{ secrets.DEV_S3_BUCKET }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region={{ secrets.DEV_REGION }}" \
          -backend-config="access_key={{ secrets.DEV_ACCESS_KEY }}" \
          -backend-config="secret_key={{ secrets.DEV_SECRET_KEY }}"

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Format Terraform Template"
        run: terraform fmt

      - name: "Get latest Prod AMI ID"
        run: |
          LATEST_AMI_ID=$(aws ec2 describe-images \
            --owners self \
            --filters 'Name=state,Values=available' \
            'Name=tag:Project,Values=${var.project_name}' \
            'Name=tag:Env,Values=${var.project_env}' \
            'Name=name,Values=${var.project_name}-${var.project_env}-*' \
            --sort-by CreationDate,DESC \
            --query 'Images[0].ImageId' \
            --output text)
          echo "Latest AMI ID: $LATEST_AMI_ID"
          echo "LATEST_AMI_ID=$LATEST_AMI_ID" >> $GITHUB_ENV

      - name: "Terraform Plan"
        run: terraform plan \
              -var-file="dev.tfvars" \
              -var="ami_id=${{ env.LATEST_AMI_ID }}"
      
      - name: "Terraform Apply"
        run: |
          terraform apply \
          -auto-approve \
          -var-file="dev.tfvars" \
          -var="ami_id=${{ env.LATEST_AMI_ID }}"
