---
name: "Dev Infra Build"

on:
  repository_dispatch:
    types: [ dev-deploy-event ]
    
  push:
    branches:
      - dev

jobs:

  build:
    runs-on: self-hosted
    env:
      terraform_version: "1.6.2"
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_SECRET_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.DEV_REGION }}

    steps:

      - name: "Checkout the repository"
        uses: actions/checkout@v3
      
      - name: "Nodejs installation"
        run: |
          /opt/nodejs/versions/node-v20.10.0/bin/npm init -y \
          /opt/nodejs/versions/node-v20.10.0/bin/npm install

      - name: "Terraform installation"
        uses: hashicorp/setup-terraform@v3
        with:
          version: ${{ env.terraform_version }}

      - name: "Terraform init"
        run: |
          terraform init \
          -backend-config="bucket=${{ secrets.DEV_S3_BUCKET }}" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="region=${{ secrets.DEV_REGION }}" \
          -backend-config="access_key=${{ secrets.DEV_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.DEV_SECRET_KEY }}"

      - name: "Terraform Validate"
        run: terraform validate

      - name: "Format Terraform Template"
        run: terraform fmt

      - name: "Terraform Plan"
        run: terraform plan -var-file=dev.tfvars
      
      - name: "Terraform Apply"
        run: |
          terraform apply \
          -auto-approve \
          -var-file=dev.tfvars
